#ifndef CPPSTEAMTOOLS_GLOBAL_H
#define CPPSTEAMTOOLS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CPPSTEAMTOOLS_LIBRARY)
#define CPPSTEAMTOOLS_EXPORT Q_DECL_EXPORT
#else
#define CPPSTEAMTOOLS_EXPORT Q_DECL_IMPORT
#endif

#endif // CPPSTEAMTOOLS_GLOBAL_H
